import { LazyAuxQueryRunner } from '@/core/auxiliary/LazyAuxQueryRunner';
import type {
  AuxiliaryPurpose,
  ProviderAuxiliarySource,
} from '@/core/auxiliary/ProviderAuxiliarySource';
import { QueryBackedInlineEditService } from '@/core/auxiliary/QueryBackedInlineEditService';
import { QueryBackedInstructionRefineService } from '@/core/auxiliary/QueryBackedInstructionRefineService';
import { QueryBackedTitleGenerationService } from '@/core/auxiliary/QueryBackedTitleGenerationService';
import {
  UnsupportedInlineEditService,
  UnsupportedInstructionRefineService,
  UnsupportedTitleGenerationService,
} from '@/core/auxiliary/UnsupportedAuxiliaryServices';
import { providerCatalog } from '@/core/providers/ProviderCatalog';
import type {
  InlineEditService,
  InstructionRefineService,
  TitleGenerationCallback,
  TitleGenerationService,
} from '@/core/providers/types';
import type { ProviderId } from '@/core/types/provider';

export interface AuxiliaryExecutionOwnerOptions {
  /**
   * What each provider contributes. A provider that is absent cannot do
   * auxiliary work, and the services this hands out say so.
   */
  readonly sources: ReadonlyMap<ProviderId, ProviderAuxiliarySource>;
  /**
   * Which provider a title is generated by, read at the moment one is asked
   * for. Injected rather than resolved here: the answer comes from model
   * ownership, which is still a registry row, and this owner should not
   * acquire that dependency only to hand it back.
   */
  resolveTitleProviderId(): ProviderId;
}

/**
 * Every auxiliary service the application hands out, and the only place they
 * are built.
 *
 * Nine providers each registered three factories over the plugin — twenty-seven
 * constructors for three services, of which nine were the same three no-ops
 * with a name changed and fifteen were the same wrapper around a runner. What
 * varies between providers is the runner and the title model; this is the rest,
 * once.
 *
 * It takes no plugin. The compositions that own a provider's processes are what
 * supply the runners, which is the whole reason these had to reach for the
 * plugin before: the composition was reachable only through it.
 */
export class AuxiliaryExecutionOwner {
  constructor(private readonly options: AuxiliaryExecutionOwnerOptions) {}

  /**
   * The owner a caller gets when the application has not composed one.
   *
   * Between plugin load and the kernel starting — and after unload — there is
   * no composition to take a runner from. A caller that asked for a service
   * then used to get one built over a plugin that could not answer; it gets one
   * that says so instead.
   */
  static unavailable(providerId: ProviderId): AuxiliaryExecutionOwner {
    return new AuxiliaryExecutionOwner({
      resolveTitleProviderId: () => providerId,
      sources: new Map(),
    });
  }

  /**
   * A title service that routes per title, not per tab.
   *
   * The provider is resolved when a title is asked for, because the model that
   * decides it is a setting the user can change while a tab is open — and a tab
   * holds its title service for its whole life.
   */
  titleGenerationService(): TitleGenerationService {
    return new RoutedTitleGenerationService(() => {
      const providerId = this.options.resolveTitleProviderId();
      return this.titleServiceFor(providerId);
    });
  }

  titleServiceFor(providerId: ProviderId): TitleGenerationService {
    const source = this.options.sources.get(providerId);
    if (!source) {
      return new UnsupportedTitleGenerationService(displayName(providerId));
    }
    return new QueryBackedTitleGenerationService({
      createRunner: () => source.createRunner('title'),
      ...(source.resolveTitleModel
        ? { resolveModel: () => source.resolveTitleModel?.() }
        : {}),
    });
  }

  instructionRefineService(providerId: ProviderId): InstructionRefineService {
    const runner = this.lazyRunner(providerId, 'instruction-refine');
    return runner
      ? new QueryBackedInstructionRefineService(runner)
      : new UnsupportedInstructionRefineService(displayName(providerId));
  }

  inlineEditService(providerId: ProviderId): InlineEditService {
    const runner = this.lazyRunner(providerId, 'inline-edit');
    return runner
      ? new QueryBackedInlineEditService(runner)
      : new UnsupportedInlineEditService(displayName(providerId));
  }

  /**
   * Built when a question is asked, not when the service is.
   *
   * A refine service is constructed when a tab initializes and an inline-edit
   * service when a modal opens; the runner behind it reaches a composition that
   * may not have finished starting. Deferring it keeps a failure where it can
   * be reported — in the answer — instead of in a constructor nobody is
   * watching.
   */
  private lazyRunner(providerId: ProviderId, purpose: AuxiliaryPurpose): LazyAuxQueryRunner | null {
    const source = this.options.sources.get(providerId);
    return source ? new LazyAuxQueryRunner(() => source.createRunner(purpose)) : null;
  }
}

function displayName(providerId: ProviderId): string {
  return providerCatalog().displayNameOrId(providerId);
}

/**
 * One title at a time per conversation, whichever provider generates it.
 *
 * Moved here from the registry unchanged: the previous title for a conversation
 * is cancelled when a new one starts, and a callback from a superseded
 * generation is dropped rather than allowed to overwrite the title the newer
 * one is about to produce.
 */
class RoutedTitleGenerationService implements TitleGenerationService {
  private readonly activeGenerations = new Map<string, TitleGenerationService>();

  constructor(private readonly resolveService: () => TitleGenerationService) {}

  async generateTitle(
    conversationId: string,
    userMessage: string,
    callback: TitleGenerationCallback,
  ): Promise<void> {
    const service = this.resolveService();
    const previous = this.activeGenerations.get(conversationId);
    this.activeGenerations.set(conversationId, service);
    previous?.cancel();

    try {
      await service.generateTitle(conversationId, userMessage, async (convId, result) => {
        if (this.activeGenerations.get(conversationId) !== service) {
          return;
        }
        await callback(convId, result);
      });
    } finally {
      if (this.activeGenerations.get(conversationId) === service) {
        this.activeGenerations.delete(conversationId);
      }
    }
  }

  cancel(conversationId?: string): void {
    if (conversationId !== undefined) {
      // Only that conversation's: the service it routed to may be shared with
      // none, but the routing table is shared with every tab, and cancelling
      // through the whole of it took every other title down with this one.
      const service = this.activeGenerations.get(conversationId);
      if (!service) return;
      this.activeGenerations.delete(conversationId);
      service.cancel(conversationId);
      return;
    }

    const services = new Set(this.activeGenerations.values());
    this.activeGenerations.clear();
    for (const service of services) {
      service.cancel();
    }
  }
}
